using static System.Convert;
using static SplashKitSDK.SplashKit;

int dollarsWeekly;
string title;
string userInput;
double dollarsGoal;
int time;
int dollarsCurrent;
double dollarsSave;
double weeksSave;
WriteLine("What are you saving For? Enter title: ");
title = ReadLine();
WriteLine("How much do you need to save? Enter dollars: $");
userInput = ReadLine();
dollarsGoal = ToInt32(userInput);
WriteLine("");
WriteLine("How long before the purchase? Enter weeks: ");
userInput = ReadLine();
time = ToInt32(userInput);
WriteLine("How much do you have already? Enter dollars: $");
userInput = ReadLine();
dollarsCurrent = ToInt32(userInput);
WriteLine("How much can you save each week? Enter dollars: $");
userInput = ReadLine();
dollarsSave = ToInt32(userInput);
dollarsWeekly = ToInt32(dollarsGoal - dollarsCurrent) / time;
weeksSave = ToDouble(dollarsGoal / dollarsSave);
WriteLine("");
WriteLine($"For the {title}, you need to save {dollarsWeekly} dollars a week");
WriteLine($"Based on current savings you will need {weeksSave} weeks to save ${dollarsGoal}");